### ISSUE TITLE
cargo install fails with "`Self` struct constructors are unstable"

### ISSUE THREAD

**Issue by duckdalbe** [d-e-s-o/ssh-gpg-agent#1]
I'd really like to try ssh-gpg-agent, but `cargo install` leads to

```rust
   Compiling ssh-gpg-agent v0.1.1
error[E0658]: `Self` struct constructors are unstable (see issue #51994)
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ssh-gpg-agent-0.1.1/src/error.rs:139:5
    |
139 |     Self(e.0, e.1.into())
    |     ^^^^
    |
    = help: add #![feature(self_struct_ctor)] to the crate attributes to enable

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: failed to compile `ssh-gpg-agent v0.1.1`, intermediate artifacts can be found at `/tmp/cargo-installTb414q`
```

Using:
* cargo 1.32.0-nightly (b3d0b2e54 2018-11-15)
* rustc 1.32.0-nightly (6bfb46e4a 2018-11-26)
* rustup 1.17.0

Can you help me fixing this? Can I help you?

**Comment by d-e-s-o** [comment]
If I recall correctly the feature being used got stable with 1.32. That's why the README says 1.32+. I don't think 1.32 nightly qualifies for that, as that's effectively before 1.32 stable. So you'll have to upgrade your compiler. Can you try that?

**Comment by duckdalbe** [comment]
Thank you for the hint! Updated to 1.33 using rustup, now it works.

I'm still new to rust and assumed 1.32-nightly would be "after" 1.32-stable.
